### PR TITLE
Create CHANGELOG.md

### LINKED ISSUE #119: Create a `CHANGELOG.md` to record all changes since milestone 3 and add narration

### PR DESCRIPTION
**Pull request by zywkloo**
Create CHANGELOG.md

### CODE REVIEW

**Review by phchen5 — APPROVED** [review]
nice!

**Review by MoNorouzi23 — APPROVED** [review]
great

**Review by SoloSynth1 — CHANGES_REQUESTED** [review]
Need to incorporate the latest PRs i.e. #122 & #123.

**Review by SoloSynth1 — APPROVED** [review]
merging to `main`

**Pull request merged**
