### PR TITLE
Yiwei/update readme

### LINKED ISSUE #14: Update README.md to reflect the project info

### PR DESCRIPTION
**Pull request by zywkloo**
* Add some URLs for quick access to Readme
* Add team members

### CODE REVIEW

**Review by SoloSynth1 — COMMENTED** [review]
@zywkloo Is this ready to be reviewed yet? I see its status is still in "Draft".

Edit: Nevermind, please ignore this - I saw the WIP notice at the end. My bad, sorry!

**Review by SoloSynth1 — COMMENTED** [review]
@zywkloo I think we need to put a short summary of the project, directions on how to run the analysis and a list of dependencies to the read me file. I will add them now.

**Comment by SoloSynth1** [comment]
@zywkloo Please help to see if there is anything missing that is [required](https://pages.github.ubc.ca/MDS-2023-24/DSCI_522_dsci-workflows_students/release/milestone1/milestone1.html#i.-readme.md). Thanks!

**Review by zywkloo — COMMENTED** [review]
Looks good to me

**Comment by SoloSynth1** [comment]
LGTM. Merging to `main`.

**Review by SoloSynth1 — APPROVED** [review]

**Pull request merged**
